# will be placed as <repo>/.github/workflows/github-actions-docker-hub.yml for deployment.
name: Build and Push Docker Image to Docker Hub

on:
  push:
    branches: [ "dev", "main" ]
  # pull_request:
    # branches: [ "dev", "main" ]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: docker.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ repository }}

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
#      run: docker-compose build --no-cache --force-rm
      run: docker build -t ${{ repository }} .
    - name: Test the Docker image
        #        run: docker-compose up -d
      run: docker run --name ${{ repository }} -dp 8001:8001 ${{ repository }}
#  test:
#    runs-on: ubuntu-latest
#    steps:
##      - uses: actions/checkout@v2
#      - uses: actions/checkout@v3
#      - name: Test the Docker image
##        run: docker-compose up -d
#        run: docker run --name ${{ repository }} -dp 8001:8001 ${{ repository }}
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
#        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}"
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
